
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5

staging:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 8
